### ISSUE TITLE
Use LDAP login instead of name on Discourse login

### ISSUE THREAD

**Issue by egrigolon** [jonmbake/discourse-ldap-auth#2]
Hi, first of all thanks for this great plugin, it was very easy to use.

My only comment is that when user creates a new account, it's currently using the full name (replacing spaces by _) as the discourse username. I'd like to have the ability to set it as the actually LDAP login so we can keep it consistent with the AD rules of my company.

Also, is there a way to restrict user registration only using the same LDAP username, password and e-mail address?

Thanks!

-Eugenio

**Comment by jonmbake** [comment]
Hey Eugenio.

I updated the plugin to use LDAP login as username here: https://github.com/jonmbake/discourse-ldap-auth/commit/d7e9009b940e0e8c525e9d4d7309ae9023c37715.  Unfortunately, Discourse automatically converts any periods or dashes to underscores, which is fixed in a future release, 1.5: https://github.com/discourse/discourse/commit/262f561a877e0296d7ca7f6ec9f27edd0d30ca8e.  For example, my LDAP username is `jon.bake`, but Discourse doesn't allows periods so it will convert it to `jon_bake`.

I am not sure about what you mean by restrict LDAP.  If you want to only allow login by LDAP, you can turn off local logins in the Admin Login Settings.  Discourse has a unique constraint on User username and email so there should never be a conflict between a local account and an LDAP-generated account.  If you have local login enabled, the passwords for LDAP and local login will be distinct; there is no way to share them.

Best,
Jon

**Comment by egrigolon** [comment]
Hi Jon, thanks for the update on the plugin, it worked as expected! I was wondering how I can extend it to get other LDAP info such as photo. Can you show me an example?

I was also able to make Discourse only check for LDAP logins as you mentioned. Thanks for that as well!

-Eugenio

**Comment by jonmbake** [comment]
Hey Eugenio.  The plugin wraps https://github.com/intridea/omniauth-ldap.  `Onmiauth-Ldap` does the mapping of the LDAP response to the `info` hash passed into `after_authenticate`.  The mapped values are defined by the `@@config` variable defined here: https://github.com/intridea/omniauth-ldap/blob/9d36cdb9f3d4da040ab6f7aff54450392b78f5eb/lib/omniauth/strategies/ldap.rb.  To get the image value, you would call `info[:image]` in `after_authenticate`.

**Comment by egrigolon** [comment]
Awesome Jon, thanks for help on this one.
