### ISSUE TITLE
Create Users Beforehand

### ISSUE THREAD

**Issue by B2RN** [jonmbake/discourse-ldap-auth#24]
When looking at the auth options, and the docs regarding it there's the "none" option:

"Fail auth if the user account does not already exist. This is a good option for an Admin that creates accounts ahead of time."

I'm curious how you'd go about creating accounts beforehand. We'd like to import all active accounts before launching the service, and this'd be a pretty sweet deal for us.

Do we just create an account via `User.create` or? Don't see how the password would be handled if we did that.

Either way, thanks for making the plugin. LDAP integration is sort of a must for us.

**Comment by jonmbake** [comment]
Yes, you can do it via script by calling `User.create` similar to what we do for the _list User Account Creation_ here: https://github.com/jonmbake/discourse-ldap-auth/blob/master/lib/ldap_user.rb#L31. The password doesn't need to be set since it is authenticating against LDAP, not through Discourse auth.

Another common scenario is the that the accounts already exist by the user logging in w/ a different authentication mechanism.

**Comment by B2RN** [comment]
Brilliant, thanks a bunch!
