### ISSUE TITLE
Better feedback on errors?

### ISSUE THREAD

**Issue by mgaudet** [jonmbake/discourse-ldap-auth#9]
So, in production.log, I have 

```
Started GET "/auth/ldap" for x.y.z.a at 2016-07-19 20:21:13 +0000
(ldap) Setup endpoint detected, running now.
(ldap) Request phase initiated.
Started POST "/auth/ldap/callback" for x.y.z.a at 2016-07-19 20:21:20 +0000
(ldap) Setup endpoint detected, running now.
(ldap) Callback phase initiated.
(ldap) Authentication failure! invalid_credentials encountered.
```

but the error the LDAP login box gives 

> Sorry, there was an error authorizing your account. Perhaps you did not approve authorization? 

In general, I'm slightly stymied at figuring out how to troubleshoot errors with LDAP authentication, so any suggestions on logs / errors would be appreciated. (Super glad to see this tho!)

**Comment by jonmbake** [comment]
Hey @mgaudet. It looks like that error is propagating from Discourse proper, not the plugin or `omniauth-ldap`; see https://meta.discourse.org/t/how-to-solve-this-error-sorry-there-was-an-error-authorizing-your-account-perhaps-you-did-not-approve-authorization/32599. I am not sure if there is a way for a plugin to hook into `app/controllers/users/omniautth_callbacks_controller.rb #failure` in order to provide a better error message. I am not seeing one. Let me know if you know of something.

Jon
